;;; chunk-edit-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chunk-edit.el

(autoload 'chunk-edit "chunk-edit" "\
Open or create the *chunk-edit* buffer and switch to it." t)
(autoload 'chunk-edit-insert-file "chunk-edit" "\
Insert the FILE-PATH chunk into the *chunk-edit* buffer.

(fn FILE-PATH)" t)
(autoload 'chunk-edit-insert-region "chunk-edit" "\
Insert the active region as a chunk into the *chunk-edit* buffer.
If there is no active region, insert the entire buffer content." t)
(register-definition-prefixes "chunk-edit" '("chunk-edit-"))


;;; End of scraped data

(provide 'chunk-edit-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chunk-edit-mode-autoloads.el ends here
