(package "chunk-edit"
         "0.1"
         "Edit code chunks from multiple files in one buffer")

(website-url "https://github.com/vkazanov/chunk-edit")
(keywords "tools" "convenience" "editing")

(package-file "chunk-edit.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "29.1")
(development
 (depends-on "ert-runner")
 (depends-on "elisp-lint"))
